config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
 devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

 get "users/check" => "users#check"
# scope module: :users do
resources :users do
 get 'relationships/follow' => "relationships#follow", as: "relationship_follow"
 get 'relationships/follower' => "relationships#follower", as: "relationship_follower"
  resource :relationships
 # end
end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'posts/search', to: 'posts#search'
resources :posts do
 resources :comments, only: [:create, :destroy]
end


resource :likes, only: [:create, :destroy]

resource :kawaii, only: [:create]

 
namespace :admins do
 get "top" => "admin/users#index"
  resources :users,only: [:index,:show,:edit,:destroy]
  resources :posts,only: [:index,:show,:edit,:destroy]
  resources :post_comment,only: [:destroy]


end

Rails.application.routes.draw do
  root  'inquiry#index'
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

  get 'home/about' => 'homes#about'
  
  get '/search', to: 'users#search'

  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  validates :name, presence: true
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", :dependent => :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
 
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", :dependent => :destroy
  has_many :followings, through: :relationships, source: :followed, :dependent => :destroy
  
  
  has_many :posts, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  def self.search(keyword)
    where(["name like?" , "%#{keyword}%" ])
  end
  
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
 before_action :authenticate_admin!

 def index
  @users = User.all.page(params[:page]).per(10).order(id: "DESC")
 end

 def show
  @posts = Post.all
  @user = User.find(params[:id])
 end

 def destroy
  user = User.find(params[:id])
  user.destroy
  redirect_to admins_users_path
 end

end

app/controllers/users/comments_controller.rb
class User::CommentsController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class User::RelationshipsController < ApplicationController
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

 def after_sign_in_path_for(resource)
    user_path(current_user)
 end
 
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5).order(id: "DESC")
  end
  def index
    @users = User.all.page(params[:page]).per(10).order(id: "DESC")
  end
  
  def edit
    @user = User.find(params[:id])
    # if @user != current_user
    #   redirect_to user_path(current_user.id)
    # end
  end
  
  def update
    @user = User.find(params[:id])

     if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully'
      redirect_to user_path(@user.id)
     else

      render action: :edit
     end
  end
  
  def check
      @user = User.find(current_user.id) 
  end
  
  def destroy
      @user = User.find(params[:id]) 
      @user.destroy
      flash[:notice] = 'ユーザーを削除しました。'
      redirect_to :root
  end
  
  def search
      @users = User.search(params[:keyword]).page(params[:page])
      @keyword = params[:keyword]
      render "index"
  end
  
private
 def user_params
    params.require(:user).permit(:name, :introduction, :user_image)
 end
  
  
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/relationships_helper.rb
module User::RelationshipsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/users/check.htmk.erb
<h1>退会確認ページ</h1>

<div class="font">
<div class="container">
  <div class="row mt-5">
    <div class="col-12 text-center font-weight-bold" >本当に退会しますか？</div>
  </div>

  <div class="row mt-5">
    <div class="col text-center">
      退会すると、会員登録情報や</br>
      これまでの投稿・コメントが全て削除されます。</br>
      退会する場合は、「退会する」をクリックしてください。
    </div>
  </div>

  <div class="row d-flex justify-content-center mt-5 mb-5">
    <%= link_to "退会しない", user_path(current_user), class:"mr-3 moe-btn" %>
    <%= link_to "退会する", user_path(@user), method: :delete, "data-confirm" => "本当に退会しますか？" %>
  </div>
</div>
</div>

app/views/users/check.html.erb
<div class="font">
<div class="container">
  <div class="row mt-5">
    <div class="col-12 text-center font-weight-bold" >
      <h1>本当に巣立ちますか？（退会確認）</h1>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col text-center">
      退会すると、会員登録情報や</br>
      これまでの投稿・コメントが全て削除されます。</br>
      退会する場合は、「巣立つ」をクリックしてください。
    </div>
  </div>

  <div class="row d-flex justify-content-center mt-5 mb-5">
    <%= link_to "巣箱に戻る", user_path(current_user), class:"mr-3 moe-btn" %>
    <%= link_to "巣立つ", user_path(@user), class:"mr-3 nae-btn", method: :delete, "data-confirm" => "本当に退会しますか？" %>
  </div>
</div>
</div>

app/views/users/edit.html.erb
<h1></h1>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>プロフィール</h2>
  <%= form_with model: @user, local: true do |f| %>
  <br>
  <h4>なまえ</h4>
  <%= f.text_field :name %>
  <br>
  <h4>しゃしん</h4>
  <%= f.attachment_field :user_image %>
  <br>
  <h4>さえずり</h4>
  <%= f.text_area :introduction, size: "50x8" %>
  <br>
  <br>
  <%= f.submit '羽繕い完了', class: "moe-btn" %>
  
  <% end %>

 
  
  <br>
  <p><%= link_to "巣立ち（退会）", users_check_path, class: "nae-btn" %></p>

   </div>
  </div>

 </div>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <h2>♡文鳥ファンのみなさま♡</h2>
     <div class="search-form" style = "margin-left: 25%;">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, value: @keyword %>
          <%= f.submit "よぶ！", class: "moe-btn"%>
      <% end %>
      </div>
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th style="width:20%;"></th>
          <th nowrap style="width:25%;">おなまえ</th>
          <th nowrap style="width:30%;">さえずり</th>
          <th style="width:25%;"></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
       <tr>
       <td><%= attachment_image_tag user, :user_image, format: 'jpeg', fallback: "no_image.jpg", class: "user-index-image", style:"width:100%" %></td>
      <td class="ud-middle text-break" style="vertical-align: middle; width:300px;"><%= user.name %></td>
      <td class="ud-middle text-break" style="vertical-align: middle; width:600px;"><%= user.introduction %></td>
    <!--  <td>-->
    <!--% if user.id != current_user.id %>-->
    <!--     % if current_user.following? %>-->
    <!--      %= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>-->
    <!--     % else %>-->
    <!--      %= link_to "フォローする", user_relationships_path(user.id), method: :post %>-->
    <!--     % end %>-->
    <!--    % end %>-->
    <!--  </td>-->
      <td class="ud-middle" style="vertical-align: middle; width:150px;">
       <span>
        <%= link_to "とんでいく", "/users/#{user.id}", class: "moe-btn"  %>
       </span>
      </td>
     </tr>
     <% end %>
    </tbody>
   </table>
   <%= paginate @users %>
   </div>
 </div>

app/views/users/show.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-4">
     <h2 class= text-center>♡とまりぎ♡</h2>
      <div class = text-center>
       <%= attachment_image_tag @user, :user_image, format: 'jpeg', fallback: "no_image.jpg", class: "user-index-image" %>
      </div>
        <table class="table">
         <tbody>
           <tr></tr>
            <tr>
  	         <th>おなまえ</th>
  	          <br>
  	          <th class="text-break"><%= @user.name %></th>
           </tr>
           <tr>
  	         <th>さえずり</th>
  	        </tr>
  	        <br>
  	        <tr>
  	          <td colspan="2" class="text-break"><%= @user.introduction %></td>
           </tr>
           <tr>
            <th width="135">♡追っかけ中♡</th>
             <td>
              <%= link_to user_relationship_follow_path(@user) do %>
              <%= @user.followings.count %>
              <% end %>
             </td>
           </tr>
            <th>♡ファン♡</th>
            <td>
              <%= link_to user_relationship_follower_path(@user) do %>
              <%= @user.followers.count %>
              <% end %>
            </td>
          <tr>
            <td>
             <% if @user.id != current_user.id %>
              <% if current_user.following?(@user) %>
               <%= link_to "放っておく", user_relationships_path(@user.id), method: :delete, class: "nae-btn" %>
              <% else %>
               <%= link_to "追っかける", user_relationships_path(@user.id), method: :post, class: "moe-btn" %>
              <% end %>
             <% end %>
           </td>
         </tr>

      </tbody>
     </table>

   <div class="row">
    <% if @user.id == current_user.id %> 
     <div class="btn-wrapper col-10 mx-auto">
       <div class = text-center>
        <%= link_to  "羽繕い",edit_user_path(@user.id), class: "moe-btn btn-block btn-sm btn-block mb-3 fas fa-feather" %>
       </div>
     </div>
    <% end %>
   </div>
  </div>

 <!--右側-->
      <div class="col-md-8">
        <h2>♡文鳥との幸せな日々♡</h2>
        <div class="table-responsive">
          <table class="table table-hover table-inverse">
           <thead>
            <tr>
             <th nowrap style="width:40%;">♡ぶんちょう♡</th>
             <th nowrap style="width:40%;">♡文鳥とのおもいで♡</th>
             <th nowrap style="width:10%;">♡♥♡♥</th>
             <th nowrap style="width:10%;"><i class="far fa-comment-dots"></i></th>
            </tr>
           </thead>
       <tbody>
        <% @posts.each do |post| %>
        <tr>
         <td><%= link_to post_path(post) do %>
          <%= attachment_image_tag post, :post_image, size: "200x180", format: 'jpeg', fallback: "no_image.jpg", class: "user-show-image" %>
          <% end %>
         </td>

            <td class="post-column text-break" style="vertical-align: middle;"><%= post.post_detail %></td>
            <td class="ud-middle" style="vertical-align: middle;">♡<%= post.likes.count %>
             <br>♥<%= post.kawaiis.count %>♥</td>
            <td class="ud-middle" style="vertical-align: middle;"><%= post.comments.count %></td>

         </tr>
           <% end %>

       </tbody>
      </table>
     </div>
      <%= paginate @posts %>
    </div>
  </div>
</div>