config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
 devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

 get "users/check" => "users#check"
# scope module: :users do
resources :users do
 get 'relationships/follow' => "relationships#follow", as: "relationship_follow"
 get 'relationships/follower' => "relationships#follower", as: "relationship_follower"
  resource :relationships
 # end
end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'posts/search', to: 'posts#search'
resources :posts do
 resources :comments, only: [:create, :destroy]
end


resource :likes, only: [:create, :destroy]

resource :kawaii, only: [:create]

 
namespace :admins do
 get "top" => "admin/users#index"
  resources :users,only: [:index,:show,:edit,:destroy]
  resources :posts,only: [:index,:show,:edit,:destroy]
  resources :post_comment,only: [:destroy]


end

Rails.application.routes.draw do
  root  'inquiry#index'
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

  get 'home/about' => 'homes#about'
  
  get '/search', to: 'users#search'

  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :users, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    
    validates :comment, presence: true
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    
     belongs_to :follow, class_name: "User"
     
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/kawaii.rb
class Kawaii < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
end

app/models/like.rb
class Like < ApplicationRecord
     
    belongs_to :user
    belongs_to :post
    
end

app/models/post.rb
class Post < ApplicationRecord
    
    attachment :post_image
    
    validates :post_detail, :post_image, presence: true
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :kawaiis, dependent: :destroy
    
    has_many :post_tag_relations, dependent: :destroy
    has_many :tags, through: :post_tag_relations
   
   def liked_by?(user)
    likes.where(user_id: user.id).exists?
   end
   def self.search(keyword)
    where(["post_detail like?" , "%#{keyword}%" ])
   end
    
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tag_relations, dependent: :destroy
    has_many :posts, through: :post_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  validates :name, presence: true
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", :dependent => :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
 
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", :dependent => :destroy
  has_many :followings, through: :relationships, source: :followed, :dependent => :destroy
  
  
  has_many :posts, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  def self.search(keyword)
    where(["name like?" , "%#{keyword}%" ])
  end
  
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @posts = Post.all.page(params[:page]).per(10).order(id: "DESC")
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to admins_posts_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def top
    # @user = User.find(params[:id])
  end
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save

  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    # binding.pry
    like.destroy

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    def index
        @posts = Post.all.page(params[:page]).per(10).order(id: "DESC")
        @user = current_user
    end
    
    def new
        @post = Post.new
    end
    def create
      @post = Post.new(post_params)
      @post.score = Language.get_data(post_params[:post_detail])  #この行を追加
      @post.user_id = current_user.id
      flash[:notice] = 'Post was successfully created.'
     if @post.save
      redirect_to post_path(@post)
      tags = Vision.get_image_data(@post.post_image)    
      tags.each do |tag|
      @post.tags.create(tag_name: tag)
      end
     else
      render :new
     end
    end

    def show
       @post = Post.find(params[:id])
       @user = @post.user
       @new_comment = Comment.new
       @tags = Tag.where(id: PostTagRelation.where(post_id: @post.id).pluck(:tag_id))

    end
    
  def update
    @post = Post.find(params[:id])

     if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to post_path(@post.id)
     else
      render action: :edit
     end
  end
  
  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id) 
  end
  
  def search
      @posts = Post.search(params[:keyword]).page(params[:page])
      @keyword = params[:keyword]
      render "index"
  end
    
private
  def post_params
    params.require(:post).permit(:post_image, :post_detail)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/kawaiis_helper.rb
module KawaiisHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/admins/posts/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <h2>posts</h2>


 <table class="table table-hover table-inverse">

   <thead>
     <tr>
      <th nowrap style="width:5%;">User_ID</th>
      <th nowrap style="width:10%;">User</th>
      <th nowrap style="width:35%;">Photo</th>
      <th nowrap style="width:40%;", class="title-left">Column</th>
      <th nowrap style="width:5%;">Kawaii</th>
      <th nowrap style="width:5%;">comment</th>
      <th></th>
     </tr>
   </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.user_id %></td>
            <td>
            <%= post.user.name %>
             <br><%= link_to admins_user_path(post.user) do %>
             <%= attachment_image_tag post.user, :user_image, size: "80x80", format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
             <% end %>
            </td>
            <td>
             <%= link_to admins_post_path(post) do %>
              <!--%=  attachment_image_tag post, :post_image, size: "150x100", format: 'jpeg', fallback: "no_image.jpg"  %>-->
              <%=  attachment_image_tag post, :post_image, format: 'jpeg', fallback: "no_image.jpg", class: "post-index-image", style:"width:100%" %>
             <% end %>
            </td>   
            <td class="post-column text-break"><%= post.post_detail %></td>
            <td><%= post.likes.count %></td>
           <td><%= post.comments.count %></td>
           <td><%= link_to 'Delete', admins_post_path(post.id), method: :delete %></td>
        </tr>
        <% end %>
         
    </tbody>
    <td><%= paginate @posts %></td>
</table>




    </div>
  </div>
</div>

app/views/admins/posts/show.html.erb
<div class="container px-1 px-sm-0">
 <div class="row">
  <div class="col-md-6">
   <h2>Photo</h2>
    <!--%= attachment_image_tag @post, :post_image, size: "500x400", format: 'jpeg' %>-->
    <%= attachment_image_tag @post, :post_image, format: 'jpeg', class: "post-show-image", style:"width:80%" %>
   <br>
  </div>

 <!--<div class="row">      -->
   <div class="col-md-6">
     <h2>Column</h2>
        <br>
         <div class="text-break">
          <%= @post.post_detail %>
         </div>
        <br>
         <td><%= link_to "Delete", "/admins/posts/#{@post.id}",method: :delete %></td>
        <br>
         <div class="comments">
          <p>コメント件数：<%= @post.comments.count %></p>
           <% @post.comments.each do |comment| %>
            <p><%= link_to admins_user_path(comment.user) do %>
           <%= attachment_image_tag comment.user, :user_image, size: "50x50", fallback: "no_image.jpg", size: "50x50" %><br></p>
           <% end %>
           <%= comment.user.name %>
           <%= comment.created_at.strftime('%Y/%m/%d') %>
           <br>
           <%= comment.comment %>
         <div class="comment-delete">
          <%= link_to "Delete", admins_post_comment_path(comment.id), method: :delete, local: true%>
         </div>
         <% end %> 
      </div>
    </div>
   </div>
  <!--</div>-->
</div>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>errors prohibited this user from
  <% @post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

  <div class="container">
    <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>羽繕い</h2>

        <%= form_with model: @post, url:"/posts/#{@post.id}", local:true do |f| %>

      <div class="form-group">

           <%= f.label:title,"しゃしん" %>
           <br>
           <%=f.attachment_field :post_image %>

        </div>
        
        <div class="form-group">
         <%= f.label :pose_detail,"エピソード" %>
         <br>
         <%= f.text_area :post_detail, size: "30x10",class:"form-control" %>
      </div>
         <br>
           <%= f.submit '羽繕い完了',class:"moe-btn" %>

           <br>
           <%= link_to "もどる", post_path(@post.id), class: "nae-btn" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <h2>♡かわいい文鳥たち♡</h2>
    <div class="search-form" style = "margin-left: 25%;">
      <%= form_with url: posts_search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, value: @keyword %>
          <%= f.submit "見たい！", class: "moe-btn"%>
      <% end %>
    </div>
<div class="table-responsive">
 <table class="table table-hover table-striped">
   <thead>
     <tr>
      <th nowrap style="width:10%;">ごしゅじん</th>
      <th nowrap style="width:30%;">♡ぶんちょう♡</th>
      <th nowrap style="width:35%;">♡文鳥とのおもいで♡</th>
      <th nowrap style="width:20%;">♡♥♡♥♡♥♡♥♡♥</th>
      <th nowrap style="width:5%;"><i class="far fa-comment-dots"></i></th>
     </tr>
   </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td class="ud-middle" style="vertical-align: middle;">
             <%= link_to user_path(post.user) do %>
             <%= attachment_image_tag post.user, :user_image, format: 'jpeg', fallback: "no_image.jpg", class: "user-post-index-image", style:"width:100%" %>
             <% end %>
            </td>
            
            <td class="ud-middle" style="vertical-align: middle;">
             <%= link_to post_path(post) do %>
              <%=  attachment_image_tag post, :post_image, format: 'jpeg', fallback: "no_image.jpg", class: "post-index-image", style:"width:100%" %>
             <% end %>
            </td>   
            
            <td class="post-column text-break", style="vertical-align: middle;"><%= post.post_detail %>
            <br><br>
             <span class="sentiment-score">本文の感情分析スコア<%= post.score %></span>
            </td>
            
            <td class="ud-middle" style="vertical-align: middle;">
              <% if post.user.id != current_user.id %> 
              <div id="likes_buttons_<%= post.id %>">
               <%= render 'likes/like', post: post %>
              </div>
              <% else %>
              <div>♥<%= post.likes.count %>いいね</div>
              <% end %>
              
              <div id="kawaii_buttons_<%= post.id %>">
              <%= render 'kawaiis/kawaii', post: post %>
              </div>
            </td>
            
           <td class="ud-middle" style="vertical-align: middle;"><%= post.comments.count %></td>
        <!--</tr>-->
        <% end %>

     </tbody>
    </table>
   </div>
   <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>errors prohibited this user from
  <% @post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container px-5 px-sm-0">
  
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>私のかわいい文鳥♡</h2>
   <div class="img_field">
    <%= form_with model: @post,url: posts_path,local:true do |f| %>
      <dt><%= f.label :文鳥写真,class: "control-label"  %></dt>
      <dd><%=f.attachment_field :post_image %></dd>
    <div class="group">
        <dt><%= f.label :エピソード,class: "control-label" %></dt>
        <dd><%= f.text_area :post_detail, size: "30x10", class: "form-control" %></dd>
        <p><%= f.submit "自慢する！", class: "moe-btn" %></p>
    </div>
   <% end %>
  </div>
 </div>
 </div>
</div>


<!--<h2 class="mt-3">New book</h2>-->
<!--<= form_with model:Book.new, local:true do |f| %>-->
<!--  <h4>Title</h4>-->
<!--  %= f.text_field :title %>-->
<!--  <h4>Opinion</h4>-->
<!--  %= f.text_area :body %>-->
<!--  <= f.submit 'Create Book' %>-->
<!--< end %>-->

app/views/posts/show.html.erb
<div class="container px-1 px-sm-0">

 <div class="row">
  <div class="col-md-6">
   <div class = "text-center">
    <h1>♡ぶんちょう♡</h1>
     <%= attachment_image_tag @post, :post_image, format: 'jpeg', class: "post-show-image", style:"width:100%" %>
  
      <br>
        <% @tags.each do |tag| %>
          <%= tag.tag_name %>
        <% end %>
      <br>
     <% if @user.id != current_user.id %>
     <div id="likes_buttons_<%= @post.id %>">
      <%= render 'likes/like', post: @post %>
     </div>
      <% else %>
      <p>♥<%= @post.likes.count %>いいね</p>
      <% end %>
      <div id="kawaii_buttons_<%= @post.id %>">
      <%= render 'kawaiis/kawaii', post: @post %>
      </div>
    </div>
  </div>


<!--右側-->  
  <div class="col-md-6">
   <div class="col-md-30">
     <h2>エピソード</h2>
        <br>
        <div class="text-break">
         <%= @post.post_detail %>
        </div>
         <p class="sentiment-score">本文の感情分析スコア[<%= @post.score %>]</p>
        <br>
         <% if @user.id == current_user.id %>
          <td><%= link_to "書き加える", edit_post_path(@post.id), class: "moe-btn" %></td>
          <td><%= link_to "とりさげる", post_path(@post.id), class: "nae-btn",method: :delete %></td>
         <% end %>
        <br>
       
       <div id="new-comment">
         <%= render partial: 'comments/comment', locals: { post: @post} %>
       </div>
        <br>
       <div>
         <%= form_with(model:[@post, @new_comment], url: post_comments_path(@post.id)) do |f| %>
         <%= f.text_area :comment, rows:'10',cols:"50",placeholder: "コメントをここに", id:"text_area" %>
         <br>
         <%= f.submit "声援をおくる", id:"comment_submit", class: "moe-btn" %>
         <% end %>
       </div>
            
       
    </div>
   </div>