config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
 devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

 get "users/check" => "users#check"
# scope module: :users do
resources :users do
 get 'relationships/follow' => "relationships#follow", as: "relationship_follow"
 get 'relationships/follower' => "relationships#follower", as: "relationship_follower"
  resource :relationships
 # end
end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'posts/search', to: 'posts#search'
resources :posts do
 resources :comments, only: [:create, :destroy]
end


resource :likes, only: [:create, :destroy]

resource :kawaii, only: [:create]

 
namespace :admins do
 get "top" => "admin/users#index"
  resources :users,only: [:index,:show,:edit,:destroy]
  resources :posts,only: [:index,:show,:edit,:destroy]
  resources :post_comment,only: [:destroy]


end

Rails.application.routes.draw do
  root  'inquiry#index'
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

  get 'home/about' => 'homes#about'
  
  get '/search', to: 'users#search'

  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :users, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    
    validates :comment, presence: true
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    
     belongs_to :follow, class_name: "User"
     
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/kawaii.rb
class Kawaii < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
end

app/models/like.rb
class Like < ApplicationRecord
     
    belongs_to :user
    belongs_to :post
    
end

app/models/post.rb
class Post < ApplicationRecord
    
    attachment :post_image
    
    validates :post_detail, :post_image, presence: true
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :kawaiis, dependent: :destroy
    
    has_many :post_tag_relations, dependent: :destroy
    has_many :tags, through: :post_tag_relations
   
   def liked_by?(user)
    likes.where(user_id: user.id).exists?
   end
   def self.search(keyword)
    where(["post_detail like?" , "%#{keyword}%" ])
   end
    
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tag_relations, dependent: :destroy
    has_many :posts, through: :post_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  validates :name, presence: true
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", :dependent => :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
 
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", :dependent => :destroy
  has_many :followings, through: :relationships, source: :followed, :dependent => :destroy
  
  
  has_many :posts, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  def self.search(keyword)
    where(["name like?" , "%#{keyword}%" ])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def top
    # @user = User.find(params[:id])
  end
  def about
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController

  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save

  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    # binding.pry
    like.destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/kawaiis_helper.rb
module KawaiisHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
  <h1>お問い合わせ</h1>
</div>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= f.submit '送信', class: "moe-btn" %>
      </td>
    </tr>
  </table>
  
<% end %>

app/views/inquiry/index.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <div class="page-header">
 
 <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
    <h1>お問い合わせ</h1>
  </div>

  <% if @inquiry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @inquiry.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <tr>
      <th>お名前<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :name, :size=>"60" %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email, :size=>"60" %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message, :size=>"60x10" %></td>
    </tr>
 
  <tr class="center-block">
    <th>
    </th>
    <td>
    <%= f.submit '確認', class: "moe-btn" %>
    <% end %>
    </td>

 
  </tr>
</table>

app/views/inquiry/thanks.html.erb
<div class="page-header">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>